services:
  ravendb:
    image: ravendb/ravendb:latest
    container_name: ravendb
    ports:
      - "8085:8080" # Web UI and REST API
      - "38888:38888" # TCP communication
    environment:
      - RAVEN_Setup_Mode=None
      - RAVEN_Security_UnsecuredAccessAllowed=PrivateNetwork
      - RAVEN_License_Eula_Accepted=true
    volumes:
      - ravendb_data:/var/lib/ravendb/data
      - ravendb_config:/etc/ravendb

volumes:
  ravendb_data:
  ravendb_config: